### ISSUE TITLE
Comparison with NormalizeUrl

### ISSUE THREAD

**Issue by jaimeiniesta** [mazingstudio/norma#1]
Hey there! I was wondering how this library compares to the one I currently use, NormalizeUrl, so I took the tests from there and applied them to Norma.

In case you're interested, here they are:

https://github.com/jaimeiniesta/norma/blob/normalize_url_tests/test/normalize_url_test.exs

**Comment by jaimeiniesta** [comment]
Many of the tests fail - I think Norma still doesn't deal with ports; others just fail because the options are not compatible, I'll take a deeper look into that.

**Comment by ZuraGuerra** [comment]
Thanks, @jaimeiniesta ! I'm taking a look at it right now. Thanks for the patience ✨

**Comment by ZuraGuerra** [comment]
Hi, @jaimeiniesta ! Check v1.4.2, the latest release (https://github.com/mazingstudio/norma/pull/2). By now, Norma handles every case that NormalizeUrl does.

**Comment by jaimeiniesta** [comment]
Hey, thanks a lot for that, I still haven't had a chance to look at it but it's still on my to-do list to consider this as a replacement for the library I'm currently using. Thanks!

**Comment by ZuraGuerra** [comment]
Thanks to you for pointing it out in the first place! ✨

**Comment by jaimeiniesta** [comment]
Hi @ZuraGuerra ! I hope all is well.

I finally commited myself to replace NormalizeUrl with Norma - I like it better because the code is much more readable and better structured 💪 

I've reviewed the test suite, reorganized it a bit and fixed some minor details. Here's the PR

https://github.com/mazingstudio/norma/pull/4
